### ISSUE TITLE
ModuleNotFoundError: No module named 'riva_api'

### ISSUE THREAD

**Issue by kyohoong** [nvidia-riva/sample-apps#23]
I am utilizing the latest version of riva_quickstart (v2.11.0), but I am unable to locate the "riva_api-<x.y.z>-py3-none-any.whl" file within the directory. Consequently, I proceeded to install nvidia-riva-client; however, I encountered an error upon attempting to execute the command "python3 main.py".

`Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from client.webapplication.start_web_application import start_web_application
  File "/root/riva_quickstart_v2.11.0/sample-apps/virtual-assistant/client/webapplication/start_web_application.py", line 8, in <module>
    from client.webapplication.server.server import *
  File "/root/riva_quickstart_v2.11.0/sample-apps/virtual-assistant/client/webapplication/server/server.py", line 22, in <module>
    from riva.chatbot.chatbots_multiconversations_management import create_chatbot, get_new_user_conversation_index, get_chatbot
  File "/root/riva_quickstart_v2.11.0/sample-apps/virtual-assistant/riva/chatbot/__init__.py", line 8, in <module>
    from .chatbot import *
  File "/root/riva_quickstart_v2.11.0/sample-apps/virtual-assistant/riva/chatbot/chatbot.py", line 10, in <module>
    from riva.asr.asr import ASRPipe
  File "/root/riva_quickstart_v2.11.0/sample-apps/virtual-assistant/riva/asr/__init__.py", line 8, in <module>
    from .asr import *
  File "/root/riva_quickstart_v2.11.0/sample-apps/virtual-assistant/riva/asr/asr.py", line 11, in <module>
    import riva_api.riva_audio_pb2 as ra
ModuleNotFoundError: No module named 'riva_api'`

**Comment by francois-vz** [comment]
It's a dependency issue. They haven't updated the Readme as needed.

**Comment by rthoke** [comment]
anyone solve the following issue ?
